apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.kubernetes.io/managed-by: Helm

commonAnnotations:
  meta.helm.sh/release-namespace: ${NAMESPACE}

resources:
- site-sub.yml
- postgres-sub.yml
- storageaccount-sub.yml
