apiVersion: v1
kind: Namespace
metadata:
  name: uk8ssite
---
apiVersion: v1
kind: Secret
metadata:
 name: aso-credential
 namespace: uk8ssite
stringData:
 AZURE_SUBSCRIPTION_ID: ""
 AZURE_TENANT_ID: ""
 AZURE_CLIENT_ID: ""
 AZURE_CLIENT_SECRET: ""
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: cosmos-site-rg
  namespace: uk8ssite
spec:
  location: uksouth
---
apiVersion: documentdb.azure.com/v1api20210515
kind: DatabaseAccount
metadata:
  name: cosmos-site-sqldb
  namespace: uk8ssite
spec:
  location: uksouth
  owner:
    name: cosmos-site-rg
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: uksouth
      failoverPriority: 0
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: cosmos-site-sqldb-connection-settings
        key: key
      documentEndpoint:
        name: cosmos-site-sqldb-connection-settings
        key: documentEndpoint
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabase
metadata:
  name: cosmos-site-sql-db
  namespace: uk8ssite
spec:
  location: uksouth
  owner:
    name: cosmos-site-sqldb
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: cosmos-site-sql-db
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabaseContainer
metadata:
  name: cosmos-site-sql-container
  namespace: uk8ssite
spec:
  location: uksouth
  owner:
    name: cosmos-site-sql-db
  resource:
    id: cosmos-site-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]