apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-postgresql-deployment
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}-postgresql
  replicas: 1
  template:
    metadata:
      name: ${APP_NAME}-postgresql
      labels:
        app: ${APP_NAME}-postgresql
    spec:
      containers:
        - name: ${APP_NAME}-postgresql
          image: mcr.microsoft.com/k8s/asodemos/postgresqlvotes:latest
          ports:
            - containerPort: 8080
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PASSWORD
            - name: SERVER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SERVER
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PORT
