apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "openai"
        dapr.io/app-port: "5001"
    spec:
      serviceAccountName: sa-tweet  # ensure you followed the steps in the README.md to create the service account
      containers:
      - name: api
        image: aiacrebhdfm6qwft7y.azurecr.io/openaiapi:c869a1b8ac2beca334df6d936bfc7191eb8bde0c
        ports:
        - containerPort: 5001
        env:
        - name: ENV
          value: Local
        - name: TYPE
          value: OpenAI
        - name: AZURE_KEY_VAULT_URL
          value: https://ai-kv.vault.azure.net/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
