apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
  labels:
    azure.workload.identity/use: "true"