apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  location: ${LOCATION}
---
apiVersion: v1
kind: Secret
metadata:
 name: aso-credential
 namespace: ${NAMESPACE}
stringData:
 AZURE_SUBSCRIPTION_ID: "$AZURE_SUBSCRIPTION_ID"
 AZURE_TENANT_ID: "$AZURE_TENANT_ID"
 AZURE_CLIENT_ID: "$AZURE_CLIENT_ID"
 AZURE_CLIENT_SECRET: "$AZURE_CLIENT_SECRET"
---
apiVersion: cache.azure.com/v1api20201201
kind: Redis
metadata:
  name: ${APP_NAME}-redis
  namespace: ${NAMESPACE}
spec:
  location: ${LOCATION}
  owner:
    name: ${APP_NAME}
  sku:
    family: C
    name: Basic
    capacity: 0
  enableNonSslPort: true
  minimumTlsVersion: "1.2"
  redisConfiguration:
    maxmemory-delta: "10"
    maxmemory-policy: allkeys-lru
  redisVersion: "6"
  operatorSpec: 
    secrets:
      hostName:
        name: redis-hostname
        key: hostName
      primaryKey:
        name: redis-access-key
        key: primaryKey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-front
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ${APP_NAME}-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ${APP_NAME}-front
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          valueFrom:
            secretKeyRef:
              name: redis-hostname 
              key: hostName
              optional: false
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis-access-key 
              key: primaryKey
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-front
  namespace: ${NAMESPACE}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ${APP_NAME}-front


