stages:
  - build
  - release

create_tarball:
  stage: build
  script:
    - tar -czvf release-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.tar.gz .
  artifacts:
    paths:
      - release-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.tar.gz
  only:
    - /^release.*$/
    - tags

create_release:
  stage: release
  script:
    - 'curl --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" --data "name=Release ${CI_COMMIT_REF_NAME} ${CI_COMMIT_SHORT_SHA}" --data "tag_name=${CI_COMMIT_REF_NAME}" --data "description=Release of ${CI_COMMIT_REF_NAME} ${CI_COMMIT_SHORT_SHA}" --data "assets[links][][name]=release-artifact" --data "assets[links][][url]=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/download" "${CI_PROJECT_URL}/api/v4/projects/${CI_PROJECT_ID}/releases"'
  dependencies:
    - create_tarball
  only:
    - /^release.*$/
    - tags