{{- if and .Values.job.enabled (eq .Values.job.vaultNamespace "AT39473") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}-at39473
  namespace: {{ .Values.job.namespace }}
  labels:
    app: {{ .Values.job.name }}-at39473
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.job.name }}-at39473
        azure.workload.identity/use: "true"
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: 'true'  
        vault.hashicorp.com/agent-pre-populate-only: 'true'
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: informer-create-secret
        image: {{ .Values.job.image }}
        command: ['/bin/sh', '-c']
        args:
          - |
            INFORMER_SECRET=$(cat /vault/secrets/{{ .Values.job.secretFile }})
            kubectl create secret generic {{ .Values.job.secretName }} --from-literal=.password=$INFORMER_SECRET --namespace={{ .Values.job.secretNamespace }} --dry-run=client -o yaml | kubectl apply -f -
            exit 0;
{{- end }}

{{- if and .Values.job.enabled (eq .Values.job.vaultNamespace "AT53357") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}-at53357
  namespace: {{ .Values.job.namespace }}
  labels:
    app: {{ .Values.job.name }}-at53357
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.job.name }}-at53357
        azure.workload.identity/use: "true"
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: 'true'  
        vault.hashicorp.com/agent-pre-populate-only: 'true'
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: informer-create-secret
        image: {{ .Values.job.image }}
        command: ['/bin/sh', '-c']
        args:
          - |
            INFORMER_SECRET=$(cat /vault/secrets/{{ .Values.job.secretFile }})
            kubectl create secret generic {{ .Values.job.secretName }} --from-literal=.password=$INFORMER_SECRET --namespace={{ .Values.job.secretNamespace }} --dry-run=client -o yaml | kubectl apply -f -
            exit 0;
{{- end }}