apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: cosmos-rg
  namespace: cosmos
spec:
  location: uksouth
---
apiVersion: v1
kind: Secret
metadata:
 name: aso-credential
 namespace: ${NAMESPACE}
stringData:
 AZURE_SUBSCRIPTION_ID: "$AZURE_SUBSCRIPTION_ID"
 AZURE_TENANT_ID: "$AZURE_TENANT_ID"
 AZURE_CLIENT_ID: "$AZURE_CLIENT_ID"
 AZURE_CLIENT_SECRET: "$AZURE_CLIENT_SECRET"