---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedCluster
metadata:
  creationTimestamp: null
  name: danat-aks
spec:
  aadProfile:
    adminGroupObjectIDs:
    - 809418f6-4770-45d9-8546-a41a033675c4
    enableAzureRBAC: true
    managed: true
    tenantID: 550cfcda-8a2d-452c-ba71-d6bc6bf5bb31
  addonProfiles:
    azureKeyvaultSecretsProvider:
      config:
        enableSecretRotation: "false"
        rotationPollInterval: 2m
      enabled: true
    azurepolicy:
      enabled: true
    omsagent:
      config:
        LogAnalyticsWorkspaceResourceID: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/DefaultResourceGroup-SUK/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-133d5755-4074-4d6e-ad38-eb2a6ad12903-SUK
        useAADAuth: "true"
      enabled: true
  agentPoolProfiles:
  - availabilityZones:
    - "1"
    - "2"
    - "3"
    count: 2
    enableAutoScaling: true
    enableFIPS: false
    kubeletDiskType: OS
    maxCount: 2
    maxPods: 110
    minCount: 1
    mode: System
    name: sysnpl1
    nodeTaints:
    - CriticalAddonsOnly=true:NoSchedule
    orchestratorVersion: "1.29"
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: AzureLinux
    osType: Linux
    powerState:
      code: Running
    type: VirtualMachineScaleSets
    upgradeSettings:
      maxSurge: 10%
    vmSize: Standard_D2s_v3
  - availabilityZones:
    - "1"
    count: 2
    enableAutoScaling: true
    enableFIPS: false
    kubeletDiskType: OS
    maxCount: 2
    maxPods: 30
    minCount: 1
    mode: User
    name: usrmpl1
    orchestratorVersion: "1.29"
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: AzureLinux
    osType: Linux
    powerState:
      code: Running
    type: VirtualMachineScaleSets
    upgradeSettings:
      maxSurge: 10%
    vmSize: Standard_D2s_v3
  apiServerAccessProfile:
    enablePrivateCluster: true
    enablePrivateClusterPublicFQDN: true
    privateDNSZone: system
  autoScalerProfile:
    balance-similar-node-groups: "false"
    expander: random
    max-empty-bulk-delete: "10"
    max-graceful-termination-sec: "600"
    max-node-provision-time: 15m
    max-total-unready-percentage: "45"
    new-pod-scale-up-delay: 0s
    ok-total-unready-count: "3"
    scale-down-delay-after-add: 10m
    scale-down-delay-after-delete: 10s
    scale-down-delay-after-failure: 3m
    scale-down-unneeded-time: 10m
    scale-down-unready-time: 20m
    scale-down-utilization-threshold: "0.5"
    scan-interval: 10s
    skip-nodes-with-local-storage: "false"
    skip-nodes-with-system-pods: "true"
  autoUpgradeProfile:
    nodeOSUpgradeChannel: NodeImage
    upgradeChannel: patch
  azureMonitorProfile:
    metrics:
      enabled: true
      kubeStateMetrics:
        metricAnnotationsAllowList: ""
        metricLabelsAllowlist: ""
  azureName: danat-aks
  disableLocalAccounts: true
  dnsPrefix: danat-aks-dns
  enableRBAC: true
  identity:
    type: UserAssigned
    userAssignedIdentities:
    - reference:
        armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/azwi-quickstart-f2ac/providers/Microsoft.ManagedIdentity/userAssignedIdentities/workload-identity-uami
  identityProfile:
    kubeletidentity:
      clientId: f0008cfa-3b57-4b98-ac00-0acdadaa5556
      objectId: acbe3ef4-5a51-48c0-b061-dc7915607db6
      resourceReference:
        armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/MC_aks_danat-aks_uksouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/danat-aks-agentpool
  kubernetesVersion: "1.29"
  location: uksouth
  networkProfile:
    dnsServiceIP: 10.0.0.10
    ipFamilies:
    - IPv4
    loadBalancerProfile:
      backendPoolType: nodeIPConfiguration
      effectiveOutboundIPs:
      - reference:
          armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/MC_aks_danat-aks_uksouth/providers/Microsoft.Network/publicIPAddresses/8f4df275-81f5-4eae-b5d6-b0cb1265f3a9
      managedOutboundIPs:
        count: 1
    loadBalancerSku: standard
    networkDataplane: cilium
    networkPlugin: azure
    networkPluginMode: overlay
    networkPolicy: cilium
    outboundType: loadBalancer
    podCidr: 10.244.0.0/16
    podCidrs:
    - 10.244.0.0/16
    serviceCidr: 10.0.0.0/16
    serviceCidrs:
    - 10.0.0.0/16
  nodeResourceGroup: MC_aks_danat-aks_uksouth
  oidcIssuerProfile:
    enabled: true
  privateLinkResources:
  - groupId: management
    name: management
    reference:
      armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/danat-aks/providers/Microsoft.ContainerService/managedClusters/danat-aks/privateLinkResources/management
    requiredMembers:
    - management
    type: Microsoft.ContainerService/managedClusters/privateLinkResources
  securityProfile:
    defender:
      logAnalyticsWorkspaceResourceReference:
        armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/DefaultResourceGroup-SUK/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-133d5755-4074-4d6e-ad38-eb2a6ad12903-SUK
      securityMonitoring:
        enabled: true
    imageCleaner:
      enabled: true
      intervalHours: 168
    workloadIdentity:
      enabled: true
  serviceMeshProfile:
    istio:
      components:
        ingressGateways:
        - enabled: true
          mode: Internal
        - mode: External
      revisions:
      - asm-1-20
    mode: Istio
  servicePrincipalProfile:
    clientId: msi
  sku:
    name: Base
    tier: Free
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  supportPlan: KubernetesOfficial
  windowsProfile:
    adminUsername: danat
    enableCSIProxy: true
  workloadAutoScalerProfile:
    keda:
      enabled: true
---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedClustersAgentPool
metadata:
  creationTimestamp: null
  name: danat-aks-sysnpl1
spec:
  availabilityZones:
  - "1"
  - "2"
  - "3"
  azureName: sysnpl1
  count: 2
  enableAutoScaling: true
  enableFIPS: false
  kubeletDiskType: OS
  maxCount: 2
  maxPods: 110
  minCount: 1
  mode: System
  nodeTaints:
  - CriticalAddonsOnly=true:NoSchedule
  orchestratorVersion: "1.29"
  osDiskSizeGB: 128
  osDiskType: Managed
  osSKU: AzureLinux
  osType: Linux
  owner:
    name: danat-aks
  powerState:
    code: Running
  type: Microsoft.ContainerService/managedClusters/agentPools
  upgradeSettings:
    maxSurge: 10%
  vmSize: Standard_D2s_v3
---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedClustersAgentPool
metadata:
  creationTimestamp: null
  name: danat-aks-usrmpl1
spec:
  availabilityZones:
  - "1"
  azureName: usrmpl1
  count: 2
  enableAutoScaling: true
  enableFIPS: false
  kubeletDiskType: OS
  maxCount: 2
  maxPods: 30
  minCount: 1
  mode: User
  orchestratorVersion: "1.29"
  osDiskSizeGB: 128
  osDiskType: Managed
  osSKU: AzureLinux
  osType: Linux
  owner:
    name: danat-aks
  powerState:
    code: Running
  type: Microsoft.ContainerService/managedClusters/agentPools
  upgradeSettings:
    maxSurge: 10%
  vmSize: Standard_D2s_v3
---
