---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedCluster
metadata:
  creationTimestamp: null
  name: danat-aks
spec:
  diskEncryptionSetID:
  - reference:
      armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/danat-aks/providers/Microsoft.Compute/diskEncryptionSets/danat-des
  aadProfile:
    enableAzureRBAC: true
    managed: true
    tenantID: 550cfcda-8a2d-452c-ba71-d6bc6bf5bb31
  addonProfiles:
    azureKeyvaultSecretsProvider:
      config:
        enableSecretRotation: "false"
        rotationPollInterval: 2m
      enabled: true
    azurepolicy:
      enabled: true
  agentPoolProfiles:
  - count: 2
    enableAutoScaling: true
    enableFIPS: false
    enableNodePublicIP: false
    kubeletDiskType: OS
    maxCount: 5
    maxPods: 110
    minCount: 2
    mode: System
    name: agentpool
    orchestratorVersion: 1.29.4
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: AzureLinux
    osType: Linux
    powerState:
      code: Running
    type: VirtualMachineScaleSets
    upgradeSettings:
      maxSurge: 10%
    vmSize: Standard_D2s_v3
  apiServerAccessProfile:
    enablePrivateCluster: true
    enablePrivateClusterPublicFQDN: true
    privateDNSZone: system
  autoScalerProfile:
    balance-similar-node-groups: "false"
    expander: random
    max-empty-bulk-delete: "10"
    max-graceful-termination-sec: "600"
    max-node-provision-time: 15m
    max-total-unready-percentage: "45"
    new-pod-scale-up-delay: 0s
    ok-total-unready-count: "3"
    scale-down-delay-after-add: 10m
    scale-down-delay-after-delete: 10s
    scale-down-delay-after-failure: 3m
    scale-down-unneeded-time: 10m
    scale-down-unready-time: 20m
    scale-down-utilization-threshold: "0.5"
    scan-interval: 10s
    skip-nodes-with-local-storage: "false"
    skip-nodes-with-system-pods: "true"
  autoUpgradeProfile:
    nodeOSUpgradeChannel: NodeImage
    upgradeChannel: patch
  azureMonitorProfile:
    metrics:
      enabled: true
      kubeStateMetrics:
        metricAnnotationsAllowList: ""
        metricLabelsAllowlist: ""
  azureName: danat-aks
  disableLocalAccounts: true
  dnsPrefix: danat-aks-dns
  enableRBAC: true
  identity:
    type: UserAssigned
    userAssignedIdentities:
    - reference:
        armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/azwi-quickstart-f2ac/providers/Microsoft.ManagedIdentity/userAssignedIdentities/workload-identity-uami
  identityProfile:
    kubeletidentity:
      clientId: f542869f-77ed-44c6-96f2-b30a7628bce6
      objectId: 09c51b4b-c941-4145-acc1-479dc7730379
      resourceReference:
        armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/MC_danat-aks_danat-aks_uksouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/danat-aks-agentpool
  kubernetesVersion: 1.29.4
  location: uksouth
  networkProfile:
    dnsServiceIP: 10.0.0.10
    ipFamilies:
    - IPv4
    loadBalancerProfile:
      backendPoolType: nodeIPConfiguration
      effectiveOutboundIPs:
      - reference:
          armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/MC_danat-aks_danat-aks_uksouth/providers/Microsoft.Network/publicIPAddresses/230e1ff8-e586-4bcc-921b-470f11d3c953
      managedOutboundIPs:
        count: 1
    loadBalancerSku: Standard
    networkDataplane: azure
    networkPlugin: azure
    networkPolicy: azure
    outboundType: loadBalancer
    serviceCidr: 10.0.0.0/16
    serviceCidrs:
    - 10.0.0.0/16
  nodeResourceGroup: MC_danat-aks_danat-aks_uksouth
  oidcIssuerProfile:
    enabled: false
  privateLinkResources:
  - groupId: management
    name: management
    reference:
      armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourcegroups/danat-aks/providers/Microsoft.ContainerService/managedClusters/danat-aks/privateLinkResources/management
    requiredMembers:
    - management
    type: Microsoft.ContainerService/managedClusters/privateLinkResources
  securityProfile: {}
  servicePrincipalProfile:
    clientId: msi
  sku:
    name: Base
    tier: Free
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  supportPlan: KubernetesOfficial
  windowsProfile:
    adminUsername: azureuser
    enableCSIProxy: true
  workloadAutoScalerProfile: {}
---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedClustersAgentPool
metadata:
  creationTimestamp: null
  name: danat-aks-agentpool
spec:
  azureName: agentpool
  count: 2
  enableAutoScaling: true
  enableFIPS: false
  enableNodePublicIP: false
  kubeletDiskType: OS
  maxCount: 5
  maxPods: 110
  minCount: 2
  mode: System
  orchestratorVersion: 1.29.4
  osDiskSizeGB: 128
  osDiskType: Managed
  osSKU: AzureLinux
  osType: Linux
  owner:
    name: danat-aks
  powerState:
    code: Running
  type: Microsoft.ContainerService/managedClusters/agentPools
  upgradeSettings:
    maxSurge: 10%
  vmSize: Standard_D2s_v3
---
