apiVersion: containerservice.azure.com/v1api20231102preview
kind: ManagedCluster
metadata:
  name: clustername
  namespace: default
spec:
  location: westus3
  owner:
    name: aso-sample-rg
  aadProfile:
    manged: true
    adminGroupObjectIDs:
      - id1
      - id2
    enableAzureRBAC: true
  diskEncryptionSetReference:
    # Can use below group-kind-name if you have imported the disk encryption set into ASO, otherwise you can use a raw ARM ID.
    # group:
    # kind:
    # name:
    armId: <id>
  autoUpgradeProfile:
    upgradeChannel: stable
    nodeOSUpgradeChannel: NodeImage
    