apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ubs-system
  name: read-only-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ubs-system
  name: admin-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
  namespace: ubs-system
subjects:
- kind: ServiceAccount
  name: vault-sa
  namespace: ubs-system
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: ubs-system
subjects:
- kind: ServiceAccount
  name: vault-sa
  namespace: ubs-system
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
