name: Build and Deploy UI

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "webui/**"

env:
  PREFIX: ai
  RG: rg-aca-openai
  ACR: aiacrebhdfm6qwft7y.azurecr.io

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ACR }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./webui
        push: true
        tags: | 
          ${{ env.ACR }}/openaiui:${{ github.sha }}
          ${{ env.ACR }}/openaiui:latest
          

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Azure login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n $PREFIX-webui -g $RG --image $ACR/openaiui:${{ github.sha }}
